### ISSUE TITLE
Database sync gives me errors

### ISSUE THREAD

**Issue by ghost** [nwalters512/wildrank-android-v2#12]

**Comment by ghost** [comment]
Tells me to check logcat

**Comment by nwalters512** [comment]
You'll need to provide more information if you want us to have any hope of helping you. When it errors, immediately eject and disconnect the flash drive and connect the device to a computer with Android Studio open. Scroll back in Logcat until you see the stack trace for the error; please post it here.

**Comment by ghost** [comment]
```
09-11 14:19:54.766 23686-30212/org.wildstang.wildrank.androidv2 W/System.err: java.lang.NullPointerException: Attempt to get length of null array
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:351)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at com.couchbase.lite.Manager.<init>(Manager.java:139)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.data.DatabaseManager.getExternalDatabase(DatabaseManager.java:129)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.syncDatabases(SyncActivity.java:75)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.access$100(SyncActivity.java:31)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:323)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:318)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err: java.lang.Exception: Error opening database!
09-11 14:19:54.767 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.data.DatabaseManager.getExternalDatabase(DatabaseManager.java:138)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.syncDatabases(SyncActivity.java:75)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.access$100(SyncActivity.java:31)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:323)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:318)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 14:19:54.768 23686-30212/org.wildstang.wildrank.androidv2 W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-11 14:19:54.877 23686-23716/org.wildstang.wildrank.androidv2 V/RenderScript: 0xa0830000 Launching thread(s), CPUs 4
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err: java.lang.NullPointerException: Attempt to get length of null array
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at com.couchbase.lite.Manager.upgradeOldDatabaseFiles(Manager.java:351)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at com.couchbase.lite.Manager.<init>(Manager.java:139)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.data.DatabaseManager.getExternalDatabase(DatabaseManager.java:129)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.syncDatabases(SyncActivity.java:75)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.access$100(SyncActivity.java:31)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:323)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:318)
09-11 14:20:37.098 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 14:20:37.099 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 14:20:37.106 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 14:20:37.106 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 14:20:37.107 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 14:20:37.107 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-11 14:20:37.107 23686-30761/org.wildstang.wildrank.androidv2 W/System.err: java.lang.Exception: Error opening database!
09-11 14:20:37.108 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.data.DatabaseManager.getExternalDatabase(DatabaseManager.java:138)
09-11 14:20:37.108 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.syncDatabases(SyncActivity.java:75)
09-11 14:20:37.108 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity.access$100(SyncActivity.java:31)
09-11 14:20:37.108 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:323)
09-11 14:20:37.108 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at org.wildstang.wildrank.androidv2.activities.SyncActivity$SyncTask.doInBackground(SyncActivity.java:318)
09-11 14:20:37.109 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
09-11 14:20:37.109 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-11 14:20:37.109 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
09-11 14:20:37.109 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-11 14:20:37.109 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-11 14:20:37.109 23686-30761/org.wildstang.wildrank.androidv2 W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

**Comment by nwalters512** [comment]
Did you fix https://github.com/wildstang/wildrank-desktop/issues/9 before you attempted this? If the desktop app failed at properly initializing the database on the flash drive, then things will indeed behave badly.

**Comment by ghost** [comment]
I did

**Comment by ghost** [comment]
I added the folder it couldn't make a file in. It has the database.

**Comment by nwalters512** [comment]
This is in the Couchbase internals, so debugging will be a little tricky.

We _may_ have to upgrade the version of CBL in case that's a bug that's been fixed recently. May depend on https://github.com/wildstang/wildrank-desktop/pull/10

**Comment by ghost** [comment]
How long do you think it will take?

**Comment by ghost** [comment]
Will the changes be done on here too or will they just stay on windows

**Comment by nwalters512** [comment]
> We may have to upgrade the version of CBL in case that's a bug that's been fixed recently.

So potentially both. Regardless, each should be bumped to the latest version eventually.

**Comment by ghost** [comment]
If I wanted to do this myself how would I do it.

**Comment by Goofybud16** [comment]
@MrSkeletal123 If you use the latest master of both wildrank-desktop and wildrank-android, does this still occur?
